apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - otel-collector-secret-dt.yaml
  - otel-collector-rbac.yaml
  - otel-collector-dt.yaml
  - otel-demo.yaml